// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="partitioner,hls_ip_2014_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z100ffg900-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.973000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

module partitioner (
        key_in,
        request_V,
        key_out
);

parameter    ap_true = 1'b1;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input  [15:0] key_in;
output  [7:0] request_V;
output  [15:0] key_out;

wire   [2:0] tmp_1_fu_57_p1;
wire   [7:0] tmp_1_cast_fu_61_p1;
wire   [12:0] tmp_2_fu_72_p4;



assign key_out = $unsigned(tmp_2_fu_72_p4);
assign request_V = ap_const_lv8_1 << tmp_1_cast_fu_61_p1;
assign tmp_1_cast_fu_61_p1 = $unsigned(tmp_1_fu_57_p1);
assign tmp_1_fu_57_p1 = key_in[2:0];
assign tmp_2_fu_72_p4 = {{key_in[ap_const_lv32_F : ap_const_lv32_3]}};


endmodule //partitioner

